apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-sm
  labels:
    release: prometheus-stack
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: product-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
