apiVersion: v1
kind: Service
metadata:
  name: stock-service-svc
  labels:
    app: stock-service
spec:
  type: NodePort
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
